name: HokkaidoMountainExperience
favicon: null
layout_spectrum: 0.8452250196132809
typography_spectrum: 0.33336318121291697
title: Hokkaido Mountain Experience
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f4f3'
    - '#94aac3'
    - '#444447'
    - '#1073b5'
    - '#e81917'
  brandStrength: 0.6910679673310369
  lightness: 0.8187375336419791
  saturation: 0.8124293726868927
  rhythmicContrast: 0.2246637020725757
purpose: []
